---
- name: Copy /etc/rc.local if not exists
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: "0755"
    force: no
    backup: yes
  register: rclocalcreated


- name: Enable rc-local
  service:
    name: rc-local
    enabled: yes
    state: restarted

